spring:
  redis:
    host: ${REDIS_HOST:localhost} # Por defecto, localhost
    port: ${REDIS_PORT:6379} # Por defecto, puerto 6379
    password: ${REDIS_PASSWORD:} # Por defecto, vacío
    timeout: 2000ms
  main:
    allow-bean-definition-overriding: true
  logging:
    level:
      org.springframework: DEBUG
      org.apache.catalina: DEBUG
      org.apache.tomcat: DEBUG
    file:
      name: logs/spring-boot-app.log
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
