spring:
  redis:
    host: localhost
    port: 6379
    password: "" # Si no tienes contraseña, déjalo vacío
    timeout: 2000ms
  main:
    allow-bean-definition-overriding: true
  logging:
    level:
      org.springframework: DEBUG
      org.apache.catalina: DEBUG
      org.apache.tomcat: DEBUG
    file:
      name: logs/spring-boot-app.log
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

